apiVersion: v1
kind: Service
metadata:
  name: springboot-restapi
  labels:
    app: springboot-restapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: springboot-restapi
