apiVersion: v1
kind: Service
metadata:
  name: springboot-restapi
#  labels:
#    app: springboot-restapi
spec:
  $patch: replace
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007
  selector:
    app: springboot-restapi

