apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-restapi-deploy
  labels:
    app: springboot-restapi-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-restapi
  template:
    metadata:
      labels:
        app: springboot-restapi
    spec:
      containers:
      - name: springboot-restapi
        image: gcr.io/mypractice-353108/studyspringboot-main:efb4e5b
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
